- name: deploying python app on the minikube cluster
  hosts: all
  tasks:
  #- name: delete the old deployment
  #  command: kubectl delete -f /home/ubuntu/deployment.yml
  #- name: delete the old service
  #  command: kubectl delete -f /home/ubuntu/service.yml
   - name: creating the new deployment 
     command: kubectl apply -f /home/ubuntu/deployment.yml
   - name: creating the new service
     command: kubectl apply -f /home/ubuntu/service.yml
