apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deploy
spec:
 replicas: 2
 selector:
  matchLabels:
   app: python
 template:
  metadata:
   labels:
    app: python
 spec:
  containers:
   - name: python-app
     image: chkvijay/pipeline-build
     imagePullPolicy: Always
     ports:
      - containerPort: 8000

 
