apiVersion: v1
kind: Service
metadata:
 name: python-service
 labels:
  app: python
spec:
 type: LoadBalancer
 ports:
  - targetPort: 8000
    port: 8000
    nodePort: 31200
 selector:
  app: python

